# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: user
    #   POSTGRES_PASSWORD: example
    #   POSTGRES_DB: testdb
    volumes:
      - db-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-volume: